In [1]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

import warnings
warnings.filterwarnings('ignore')

# olx.com

In [2]:
driver = webdriver.Chrome(r"C:\Users\harsh\Desktop\chromedriver.exe")
driver.maximize_window()

In [3]:
# Opening the homepage of Amazon.in
url = "https://www.olx.in/"
driver.get(url)

time.sleep(2)

In [4]:
#search bar
search = driver.find_element_by_xpath('//*[@id="container"]/header/div/div/div[2]/div/div/div[2]/div/form/fieldset/div/input')
search.send_keys("cars")
button= driver.find_element_by_xpath('//div[@class="_3b3oR"]')
button.click()

In [6]:
#Product url
product_urls = []
start=0
end=15
for page in range(start,end):#for loop for scrapping 3 page
    url=driver.find_elements_by_xpath('//li[@class="EIR5N"]/a')       #scraping urls
    for i in url:
        product_urls.append(i.get_attribute("href"))                        #appending the urls in product_urls list
    nxt_button=driver.find_element_by_xpath('//div[@class="JbJAl"]/button')     #scraping the list of buttons from the page
    nxt_button.click()
    time.sleep(2)

len(product_urls)

2231

In [7]:
#Make empty lists
Brand = []   
manufactured_year = []
variant= []
kilometers = []
fuel = []
location = []
price = []
owners = []

In [8]:

for i in product_urls:
    driver.get(i)
    time.sleep(0.5)
    
    # Extracting Brand from xpath
    try:
        brand = driver.find_element_by_xpath('//div[@class="_35xN1"]')      
        Brand.append(brand.text)
    except NoSuchElementException:
        Brand.append('-')    

    # Extracting varient from xpath
    try:
        vari = driver.find_element_by_xpath('//div[@class="_3tLee"]')      
        variant.append(vari.text)
    except NoSuchElementException:
        variant.append('-') 

     # Extracting driven kilometers
    try:
        km = driver.find_element_by_xpath('//div[@class="aOxkz"]/div[2]/div')      
        kilometers.append(km.text)
    except NoSuchElementException:
        kilometers.append('-') 

     # Extracting fuel from xpath
    try:
        fl = driver.find_element_by_xpath('//div[@class="aOxkz"]/div[1]/div')      
        fuel.append(fl.text)
    except NoSuchElementException:
        fuel.append('-')    

      #Location
    try:
        locat = driver.find_element_by_xpath('//div[@class="_1ThNy"][2]/div[2]/div[2]')      
        location.append(locat.text)
    except NoSuchElementException:
        location.append('-')    
  
     #Price
    try:
        pz = driver.find_element_by_xpath('//div[@class="_3FkyT"]')      
        price.append(pz.text)
    except NoSuchElementException:
        price.append('-')    

    #number of owners
    try:
        oner = driver.find_element_by_xpath('//div[@class="_1l939"]/div[1]/div[2]/div[2]')      
        owners.append(oner.text)
    except NoSuchElementException:
        owners.append('-')  

        
    #manufactured_year
    manufactured = []
    try:
        manufactur = driver.find_element_by_xpath('//div[@class="_35xN1"]')      
        manufactured.append(manufactur.text)
    except NoSuchElementException:
        manufactured.append('-')
    for j in manufactured:
        manufactured_year.append(j[-5:-1])
        
        
    
print(len(Brand),len(manufactured_year),len(variant),len(kilometers),len(fuel),len(location),len(price),len(owners))

2231 2231 2231 2231 2231 2231 2231 2231

In [9]:
data = pd.DataFrame({'Brand':Brand,'Variant':variant,'Manufactured_year':manufactured_year,'Kilometers':kilometers,
                    'Fuel':fuel,'location':location,'price':price,'owners':owners})
data

,Brand,Variant,Manufactured_year,Kilometers,Fuel,location,price,owners
0,Hyundai I10 (2012),1.2 Kappa Magna,2012,55000.0 KM,PETROL,"Sector 31, Noida","₹ 2,75,000",1st
1,Skoda Rapid (2020),Others,2020,"41,000 KM",PETROL,"Old SBI Colony, Anantapur","₹ 9,50,000",1st
2,-,-,,-,-,-,-,-
3,Ford Fiesta (2007),2004-2010 1.4 Duratorq ZXI,2007,90000 KM,DIESEL,"Saket Nagar, Indore","₹ 2,10,000",First
4,Maruti Suzuki Wagon R (2015),1.0 LXi (O),2015,30000 KM,CNG,"Antop Hill, Mumbai","₹ 2,00,000",Second
...,...,...,...,...,...,...,...,...
2226,Maruti Suzuki 800 (1992),Duo Std LPG,1992,"56,900 KM",PETROL,"Baranduru, Bhadravati","₹ 35,000",4+
2227,Other Brands Others (2018),,2018,"39,000 KM",PETROL,"Kalachand Bazar, Maibong","₹ 1,20,000",1st
2228,Maruti Suzuki Swift Dzire (2015),VDI,2015,"88,000 KM",DIESEL,"Balotra Industrial Area, Balotra","₹ 5,21,000",1st
2229,Toyota Fortuner (2013),3.0 4x2 Automatic,2013,111000.0 KM,DIESEL,"Chandigarh Airport Area, Chandigarh","₹ 14,40,000",1st
2230,Tata Others (2009),,2009,"150,000 KM",DIESEL,"Tarapur VII, Silchar","₹ 3,00,000",--

In [10]:
data.to_csv("car_olx.csv")